name: 'Increment SemVer Patch Version and Tag'
description: 'Creates a new tag with increased patch version. Expects SemVer X.Y.Z'
branding:
  icon: 'play'
  color: 'purple'
inputs:
  GITHUB_TOKEN:  # id of input
    description: 'Github Token for authentication'
    required: true
  repositoryName: # id of input
    description: 'Repository Name for tag lookup'
    required: true
  repositoryOwner: # id of input
    description: 'owner of the repository'
    required: true
  sha: # id of input
    description: 'sha id for tag creation'
    required: true

outputs:
  newTag: # id of output
    description: 'The new tag that was generated'
runs:
  using: 'node16'
  main: 'dist/index.js'
