on: [push]

jobs:
  powerShell_echo:
    runs-on: ubuntu-latest
    name: A job to say echo in Powershell
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo Powershell action step
        uses: ./ # Uses an action in the root directory
        id: echoPowerShell
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output echo
        run: echo "The echo was ${{ steps.hello.echoPowerShell.returnEcho }}"